### ISSUE TITLE
Rename/delete dir "src/main/test"

### ISSUE THREAD

**Issue by pcarana** [NICMx/rdap-data-access-api#6]
In the mentioned directory "_src/main/test_" there are some classes used for unit tests, I have 2 observations for this:

1. This classes test objects of the core (**rdap-core**), so, they don't belong to that project?
2. The directory is placed at the same level that the main code "_src/main/java_"; looking at the other projects (**rdap-sql-provider** and **rdap-server**) they have the test classes at the directory "_src/test/java/_", which is a nice approach, so why not use the same approach in the test classes of this project?

Conclusion: if the classes are moved to the project **rdap-core** the 2nd point doesn't apply (or only applies if there are going to be some test classes for this project), if they are going to stay in this project they could be placed as mentioned in the 2nd point.

**Comment by ydahhrk** [comment]
1. Agree
2. `src/main/java` is incorrect. `src/test/java` is consistent with Maven conventions.

The source folder should be renamed as `src/test/java` regardless of whether it's moved to core or not.

Also, to whoever fixes this: Do not forget to rename the packages as well: `mx.nic.rdap.db.*` -> `mx.nic.rdap.core.*`

**Comment by TheRedTrainer** [comment]
Verified. The directory was modified from "src/main/test/" to "src/test/java" and the packages were rename in this way:

src/test/java/AddressBlockTest.java
package mx.nic.rdap.core.struct;

src/test/java/IpUtilTest.java
package mx.nic.rdap.core;

**Comment by pcarana** [comment]
Closing, fixed in Red Dog v1.2
