### ISSUE TITLE
MANIFEST is really necessary?

### ISSUE THREAD

**Issue by pcarana** [NICMx/rdap-data-access-api#7]
The manifest file placed at **src/main/resources/META-INF** seems to be useless, since it doesn't have any special data/information in it. Beside this, maven adds the default manifest file when the application is built. I suggest that this file shouldn't exist, it should be deleted just to be clear.

Taking this in consideration, the whole folder **resources** could be deleted since is going to be empty, but of course, this is something to consider by who's going to solve the issue (assuming that my opinion is useful).

**Comment by TheRedTrainer** [comment]
Verified. This file was deleted as pcarana said in this issue
